### ISSUE TITLE
divide by zero error in evaluation_DRBox.py with high confidence thresholds

### ISSUE THREAD

**Issue by usarawgi911** [ThalesAleniaSpace/DRBox_keras#10]
While decoding using the evaluation_DRBox.py, it uses `decode_detections` function from the drbox_output_decoder.py. This is done for confidence threshold `conf` from 0.1 to 0.9. However, when say the `conf` is as high as 0.9, no boxes might cross the threshold in which case `decode_detections` return an empty array, and `true_positive` as well as `false_positive` remains 0. This in turn (obviously) return divide by zero error in `precision.append(true_positive / (true_positive + false_positive))` since `true_positive + false_positive` = 0.

How do we handle such cases?
Any help will be really appreciated! Thank you

**Comment by usarawgi911** [comment]
@ppontisso Any clue here? WIll really appreciate any help. TIA

**Comment by ppontisso** [comment]
Hello, 
I think one way to handle it could be to add a very small number to the denominator of the division. 
You could do : `true_positive / (true_positive + false_positive + 1e-10)`, and if `true_positive + false_positive = 0` then the result will be `0`.
This will avoid the zero division error, while not changing the results of the other threshold.

Paul

**Comment by usarawgi911** [comment]
@ppontisso That makes sense, good little trick! Thank you :)
