### ISSUE TITLE
Error input encoder

### ISSUE THREAD

**Issue by ppontisso** [ThalesAleniaSpace/DRBox_keras#4]
I had created my own dataset using roLabelImg into xml and converted into csv with parameters: filename, width, height, cx , cy , w , h , label, and angle. While Training got error as below, can you please help. 
/Downloads/DRBox_keras-master/drbox_encoder_decoder/drbox_input_encoder.py", line 352, in __call__
    classes_one_hot = class_vectors[labels[:, class_id].astype(np.int)] # The one-hot class IDs for the ground truth boxes of this batch item
IndexError: index 160 is out of bounds for axis 0 with size 2

_Originally posted by @Rhutus in https://github.com/ThalesAleniaSpace/DRBox_keras/issues/1#issuecomment-570565401_

**Comment by ppontisso** [comment]
Hello,
How many different classes do you have in your dataset ?

Did you check the shape of "ground_truth_labels" ? You need to make sure that it is in the good format : "
ground_truth_labels (list): A python list of length `batch_size` that contains one 2D Numpy array for each batch image. Each such array has `k` rows for the `k` ground truth bounding boxes belonging to the respective image, and the data for each ground truth bounding box has the format `(class_id, cx, cy, w, h, angle), and `class_id` must be an integer greater than 0 for all boxes as class ID 0 is reserved for the background class.
"

**Comment by Rhutus** [comment]
> Hello,
> How many different classes do you have in your dataset ?
> 
> Did you check the shape of "ground_truth_labels" ? You need to make sure that it is in the good format : "
> ground_truth_labels (list): A python list of length `batch_size` that contains one 2D Numpy array for each batch image. Each such array has `k` rows for the `k` ground truth bounding boxes belonging to the respective image, and the data for each ground truth bounding box has the format `(class_id, cx, cy, w, h, angle), and `class_id` must be an integer greater than 0 for all boxes as class ID 0 is reserved for the background class.
> "

I have single class(i.e. car).

**Comment by Rhutus** [comment]
Now I am getting this error
/keras/engine/training_utils.py", line 128, in standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking input: expected input_1 to have 4 dimensions, but got array with shape (6, 1)

**Comment by Rhutus** [comment]
> Hello,
> How many different classes do you have in your dataset ?
> 
> Did you check the shape of "ground_truth_labels" ? You need to make sure that it is in the good format : "
> ground_truth_labels (list): A python list of length `batch_size` that contains one 2D Numpy array for each batch image. Each such array has `k` rows for the `k` ground truth bounding boxes belonging to the respective image, and the data for each ground truth bounding box has the format `(class_id, cx, cy, w, h, angle), and `class_id` must be an integer greater than 0 for all boxes as class ID 0 is reserved for the background class.
> "

How to ensure to generate correct ground truth it is not tilted

**Comment by ppontisso** [comment]
Hello,
I recommend you to put show_images=True on line 212 to check that bounding boxes are correct before training
