### ISSUE TITLE
Error when checking input

### ISSUE THREAD

**Issue by Rhutus** [ThalesAleniaSpace/DRBox_keras#5]
How to check input size and change in Training_DRBOX?
/keras/engine/training_utils.py", line 128, in standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking input: expected input_1 to have 4 dimensions, but got array with shape (6, 1)

Thanks in advance.
_Originally posted by @Rhutus in https://github.com/ThalesAleniaSpace/DRBox_keras/issues/4#issuecomment-571113833_

**Comment by ppontisso** [comment]
You can check outputs of the training data generator by calling it with "next(train_generator)". 

This should return a 2-tuple containing the processed batch images as its first element and the encoded ground truth boxes tensor as its second element. The second element should be 3D numpy array of shape (batch_size, #boxes, #classes + 5 + 5 + 5).

Have you tried to visualize your inputs by turning 'show_images' to True in line 212 ?
" train_dataset = DataGenerator(load_images_into_memory=False, show_images=True) "

**Comment by Rhutus** [comment]
> You can check outputs of the training data generator by calling it with "next(train_generator)".
> 
> This should return a 2-tuple containing the processed batch images as its first element and the encoded ground truth boxes tensor as its second element. The second element should be 3D numpy array of shape (batch_size, #boxes, #classes + 5 + 5 + 5).
> 
> Have you tried to visualize your inputs by turning 'show_images' to True in line 212 ?
> " train_dataset = DataGenerator(load_images_into_memory=False, show_images=True) "

Solved by changing batch size in train_generator and val_generator.

**Comment by Rhutus** [comment]
> You can check outputs of the training data generator by calling it with "next(train_generator)".
> 
> This should return a 2-tuple containing the processed batch images as its first element and the encoded ground truth boxes tensor as its second element. The second element should be 3D numpy array of shape (batch_size, #boxes, #classes + 5 + 5 + 5).
> 
> Have you tried to visualize your inputs by turning 'show_images' to True in line 212 ?
> " train_dataset = DataGenerator(load_images_into_memory=False, show_images=True) "

Thanks for the reply.
I found the solution after updating :
1) I was using images of 720 * 1280 pixels which is invalid as the requirement was of 300 * 300.
2) Batch size was inappropriate.
