### ISSUE TITLE
predict output without labels 

### ISSUE THREAD

**Issue by Rhutus** [ThalesAleniaSpace/DRBox_keras#6]
Hi ,
 
I am trying to run several images without labels as I want to run video further using .h5 file.
Getting error while running predict_DRBox.py
data_generator/object_detection_2d_data_generator.py", line 547, in generate
    if np.any(batch_y[i][:,w] <= 0) or np.any(batch_y[i][:,h] <= 0):
TypeError: 'NoneType' object is not subscriptable

How do I solve this error?
Thanks in advance.

**Comment by ppontisso** [comment]
Hello,
If you don't give any labels as input for the file predict_DRBox.py it should not give this error. What did you give as input for the prediction ?

**Comment by Rhutus** [comment]
> Hello,
> If you don't give any labels as input for the file predict_DRBox.py it should not give this error. What did you give as input for the prediction ?

Actually I want to run in a video and the model is trained successful, how to predict in a video?It would be great if it runs in a video and as video file don't have labels.

**Comment by ppontisso** [comment]
The generator is not supposed to be used on videos. You can either modify the data generator so that it can take as input a video, or create an image for each frame and run the prediction on that.

**Comment by ppontisso** [comment]
Let me know if you succeed on the prediction, I would be more than happy to see the results !

**Comment by Rhutus** [comment]
> The generator is not supposed to be used on videos. You can either modify the data generator so that it can take as input a video, or create an image for each frame and run the prediction on that.

Thanks for the reply. 
Can you please give me some reference??

**Comment by ppontisso** [comment]
I recommend you to look at OpenCV, it is a great python library to work with videos and images.
